// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BuildItemsWithConfig } from "./BuildItemsWithConfig";
import type { FoundBuildItems } from "./FoundBuildItems";

export type BuildInfo = { provided: BuildItemsWithConfig, found: FoundBuildItems, };
