// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModConfig } from "./ModConfig";
import type { TypedItem } from "./TypedItem";

export type ItemWithConfig = { config: Array<ModConfig>, item: TypedItem, };
