// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Subcategory = "Empty" | "Helmets" | "Boots" | "Gem" | "Jewel" | "Amulet" | "Belt" | "BodyArmour" | "Gloves" | "Weapon" | "LifeFlask" | "ManaFlask" | "HybridFlask" | "UtilityFlask" | "Shield" | "Quiver" | "Ring";
