[package]
name = "application"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
domain = { path = "../domain" }
tradeapi = { path = "../tradeapi" }
pob = { path = "../pob" }
thiserror = "1.0.40"
tokio = { version = "1.28.1", features = ["full"] }
serde_json = "1.0.96"
serde = { version = "1.0.163", features = ["derive"] }
