version: '3'
services:
  mongo:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - "mongodata:/data/db"

  postgres:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=poe
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - "postgresdata:/var/lib/postgresql/data"
      - "./:/poe"

  jaeger:
    image: jaegertracing/all-in-one:1.33
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686

volumes:
  mongodata:
  postgresdata:
