database:
  type: postgres
  dsn: postgres://admin:admin@localhost:5432/poe
start_change_id: "1504689493-1508009795-1458379270-1621588648-1567202746"
application:
  port: 8000
  host: 0.0.0.0
  refresh_interval_secs: 2
  enable_items_refresh: yes
  only_leagues: ["Kalandra", "Standard"]
