database:
  type: postgres
  dsn: postgres://admin:admin@localhost:5432/poe
start_change_id: "1298229149-1303699645-1259354766-1406959770-1353513412"
application:
  port: 3000
  host: 0.0.0.0
  refresh_interval_secs: 2
  enable_items_refresh: yes
  only_leagues: []
