database: "main.db"
mongo: "mongodb://localhost:27017"
start_change_id: "1298229149-1303699645-1259354766-1406959770-1353513412"
application:
  port: 3000
  host: 0.0.0.0
  refresh_interval_secs: 5
  enable_items_refresh: yes
  only_leagues: ["Scourge", "Standard"]