// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemWithConfig } from "./ItemWithConfig";

export type BuildItemsWithConfig = { helmet: ItemWithConfig, body: ItemWithConfig, boots: ItemWithConfig, gloves: ItemWithConfig, weapon1: ItemWithConfig, weapon2: ItemWithConfig, ring1: ItemWithConfig, ring2: ItemWithConfig, belt: ItemWithConfig, flasks: Array<ItemWithConfig>, gems: Array<ItemWithConfig>, jewels: Array<ItemWithConfig>, amulet: ItemWithConfig, };
