// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Category = "Flasks" | "Accessories" | "Armour" | "Jewels" | "Weapons" | "Maps" | "Currency" | "Logbook" | "Heistmission" | "Heistequipment" | "Cards" | "Monsters" | "Gems" | "Leaguestones";
