// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Config = { "Exact": number } | { "Range": { start: number, end: number, } } | { "Min": number } | { "Max": number } | "Exist";
