// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StoredItem } from "./StoredItem";

export type FoundBuildItems = { helmet: StoredItem | null, body: StoredItem | null, boots: StoredItem | null, gloves: StoredItem | null, weapon1: StoredItem | null, weapon2: StoredItem | null, ring1: StoredItem | null, ring2: StoredItem | null, belt: StoredItem | null, flasks: Array<StoredItem> | null, gems: Array<StoredItem> | null, jewels: Array<StoredItem> | null, amulet: StoredItem | null, };
