// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypedItem } from "./TypedItem";

export type FoundBuildItems = { helmet: TypedItem | null, body: TypedItem | null, boots: TypedItem | null, gloves: TypedItem | null, weapon1: TypedItem | null, weapon2: TypedItem | null, ring1: TypedItem | null, ring2: TypedItem | null, belt: TypedItem | null, flasks: Array<TypedItem> | null, gems: Array<TypedItem> | null, jewels: Array<TypedItem> | null, };
