// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemConfig } from "./ItemConfig";
import type { StoredItem } from "./StoredItem";

export type ItemWithConfig = { item: StoredItem, config: ItemConfig, };
