// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ItemConfigOption } from "./ItemConfigOption";

export type ItemConfig = { basetype: boolean, option: ItemConfigOption | null, };
