// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModOption } from "./ModOption";
import type { ModStatId } from "./ModStatId";

export type ItemConfigOption = { "Mods": { [key in ModStatId]?: ModOption } } | "Unique";
