// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TypedItem } from "./TypedItem";

export type ItemWithConfig = { item: TypedItem, };
