// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModOption = { "Exact": number } | { "Range": { start: number, end: number, } } | "Exist";
