// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModType = "Utility" | "Implicit" | "Explicit" | "Crafted" | "Enchant" | "Fractured" | "Cosmetic" | "Veiled" | "ExplicitHybrid" | "Scourge" | "Invalid";
