// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GemSearchItem } from "./GemSearchItem";

export type SearchItem = "None" | "Basetype" | "UniqueName" | { "Gem": GemSearchItem } | "Custom";
