// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Category } from "./Category";
import type { StoredItemInfo } from "./StoredItemInfo";
import type { Subcategory } from "./Subcategory";

export type StoredItem = { id: string, basetype: string, category: Category, subcategory: Subcategory, info: StoredItemInfo, name: string, };
