// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Property } from "./Property";
import type { StoredMod } from "./StoredMod";

export type StoredItemInfo = { "type": "Gem", level: number, quality: number, } | { "type": "Armor", quality: number, mods: Array<StoredMod>, properties: Array<Property>, } | { "type": "Weapon", quality: number, mods: Array<StoredMod>, properties: Array<Property>, } | { "type": "Jewel", mods: Array<StoredMod>, } | { "type": "Flask", quality: number, mods: Array<StoredMod>, } | { "type": "Accessory", quality: number, mods: Array<StoredMod>, };
