// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StoredMod = { stat_id: string, text: string, current_value_int: [number, number | null] | null, current_value_float: [number, number | null] | null, };
