[package]
name = "elixir"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
name = "elixir"
path = "src/lib.rs"

[dependencies]
rustler = "0.36"
pob = { path = "../pob" }
serde_json = "1.0.140"
thiserror = "2.0.12"
